ATTACH TABLE _ UUID 'e69a2ee3-c6ce-4914-88a4-483f3c239e9b'
(
    `ElapsedTime` Nullable(String),
    `MatchID` Nullable(String),
    `SetNo` Nullable(String),
    `GameNo` Nullable(String),
    `PointNumber` Nullable(String),
    `ServeNumber` Nullable(String),
    `Stage` Nullable(String),
    `History` Nullable(String),
    `Sentence` Nullable(String),
    `EpochTimeStart` Nullable(String),
    `EpochTimeEnd` Nullable(String),
    `MatchWinner` Nullable(String),
    `SetWinner` Nullable(String),
    `GameWinner` Nullable(String),
    `PointWinner` Nullable(String),
    `PointServer` Nullable(String),
    `ServeIndicator` Nullable(String),
    `P1Score` Nullable(String),
    `P2Score` Nullable(String),
    `P1GamesWon` Nullable(String),
    `P2GamesWon` Nullable(String),
    `P1PointsWon` Nullable(String),
    `P2PointsWon` Nullable(String),
    `P1SetsWon` Nullable(String),
    `P2SetsWon` Nullable(String),
    `PointTrack` Nullable(String),
    `SetTrack` Nullable(String),
    `P1Momentum` Nullable(String),
    `P2Momentum` Nullable(String),
    `Rally20OrMore` Nullable(String),
    `Deuces5OrMore` Nullable(String),
    `ChallengeWon` Nullable(String),
    `Ace` Nullable(String),
    `Winner` Nullable(String),
    `DoubleFault` Nullable(String),
    `UnforcedError` Nullable(String),
    `NetPoint` Nullable(String),
    `BreakPoint` Nullable(String),
    `BreakPointWon` Nullable(String),
    `BreakPointOpportunity` Nullable(String),
    `Speed_KMH` Nullable(String),
    `Speed_MPH` Nullable(String),
    `WinnerType` Nullable(String),
    `WinnerShotType` Nullable(String),
    `Court` Nullable(String),
    `CourtIndicator` Nullable(String),
    `TeamOrientStart` Nullable(String),
    `TeamOrientEnd` Nullable(String),
    `P1DistanceRun` Nullable(String),
    `P2DistanceRun` Nullable(String),
    `P1DistanceRunTotal` Nullable(String),
    `P2DistanceRunTotal` Nullable(String),
    `RallyCount` Nullable(String),
    `ServeWidth` Nullable(String),
    `ServeDepth` Nullable(String),
    `ReturnDepth` Nullable(String),
    `KickHeight` Nullable(String),
    `match` String
)
ENGINE = MergeTree
ORDER BY match
SETTINGS index_granularity = 8192
